{% set name = "dremio_client" %}
{% set version = "0.15.1a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
    path: ../
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: 5538ad5fe14ec56bf24ff2b565fa716f140921e95af59ff64032a50a45517d94

build:
  noarch: python
  number: 0
  entry_points:
    - dremio_client=dremio_client.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - click >=6.0
    - confuse
    - pandas
    - pip
    - pyarrow >=0.15.1
    - python
    - attrs
    - requests >=2.21.0
    - requests-futures
    - simplejson
    - pyodbc
  run:
    - click >=6.0
    - confuse
    - pandas
    - pyarrow >=0.15.1
    - python
    - attrs
    - requests >=2.21.0
    - requests-futures
    - simplejson
    - pyodbc

test:
  imports:
    - dremio_client
    - dremio_client.auth
    - dremio_client.conf
    - dremio_client.flight
    - dremio_client.model
    - dremio_client.util
  commands:
    - dremio_client --help

about:
  home: https://github.com/rymurr/dremio_client
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Python client for Dremio. See https://dremio.com
  doc_url: https://dremio-client.readthedocs.io/
  dev_url: https://github.com/rymurr/dremio_client

extra:
  recipe-maintainers:
    - rymurr
